FROM golang:1.26-bookworm

RUN apt-get update && apt-get install -y \
    chromium \
    --no-install-recommends \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .

CMD ["sh", "-c", "go test -json -tags e2e ./internal/e2e/... | go tool gotestfmt"]
